baseurl: https://diary.sasaplus1.com

defaultContentLanguage: ja

disableHugoGeneratorInject: true

disableKinds:
  - taxonomy
  - taxonomyTerm

enableRobotsTXT: true

footnoteReturnLinkContents: â†©

hasCJKLanguage: true

permalinks:
  posts: /posts/:year/:month/:day/:filename

pygmentsCodeFences: true
pygmentsUseClasses: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

title: diary.sasaplus1.com

uglyUrls: false
